=== JuCuAcc/XML/p03.dtd
<!ELEMENT course (title, modules*)>
<!ATTLIST course course-id (ESAD-CS | ESAD-VB | NT ) #REQUIRED >
<!ELEMENT title (#PCDATA)>
<!ELEMENT modules (module*)>
<!ELEMENT module (name, duration)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ATTLIST module moduleid ID #REQUIRED >

=== JuCuAcc/XML/p03.xml
<?xml version='1.0'?>
<!DOCTYPE course SYSTEM "p03.dtd">
<course course-id="ESAD-CS">
	<title>Enterprise System Analysis and Design using Visual C Sharp</title>
	<modules>
		<module moduleid="ESADCS-01">
			<name>Programming Concepts</name>
			<duration>80</duration>
		</module>
		<module moduleid="ESADCS-02">
			<name>Designing and implementing databases</name>
			<duration>60</duration>
		</module>
	</modules>
</course>
