=== JuCuAcc/XML/p05.dtd
<!ELEMENT persons (person*)>
<!ELEMENT person (title?, name)>
<!ELEMENT title (Mr?, Mrs?)>
<!ELEMENT Mr (#PCDATA)>
<!ELEMENT Mrs (#PCDATA)>
<!ELEMENT name (#PCDATA)>

=== JuCuAcc/XML/p05.xml
<?xml version="1.0" ?>
<!DOCTYPE persons SYSTEM "p05.dtd">

<persons> 
	<person> 
		<title>Mrs</title>
		<name>Jahanara</name>
	</person> 
	<person> 
		<name>Jahangir</name>
	</person>
	<person>
		<title>Mr</title>
		<name>Jashim</name>
	</person>
</persons>
